/**:
  ros__parameters:
    timer_period: 0.1

    warm_start_time: 0.3

    entrance_coords: [14.38, 76.21]

    # Offline data to load
    spots_data_path: "${PARKSIM_ROOT}/python/parksim/priorFiles/spots_data.pickle"
    waypoints_graph_path: "${PARKSIM_ROOT}/python/parksim/priorFiles/waypoints_graph.pickle"
    intent_model_path: "${PARKSIM_ROOT}/python/parksim/priorFiles/model/smallRegularizedCNN_L0.068_01-29-2022_19-50-35.pth"

    offline_maneuver_path: "${PARKSIM_ROOT}/python/parksim/priorFiles/parking_maneuvers.pickle"
