#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${PARKSIM_LONG_OUT_DIR:-$ROOT/experiments/qwen_vla_long_horizon/$(date +%Y%m%d_%H%M%S)}"

# This entrypoint is for realistic human-machine mixed parking-lot evaluation:
# long horizon, many entering/exiting tasks, restored static obstacles as
# departing vehicles, and hidden rule-agent intentions.
export PARKSIM_BENCH_OUT_DIR="$OUT_DIR"
export PARKSIM_BENCH_DURATION="${PARKSIM_LONG_DURATION:-900s}"
export PARKSIM_BENCH_LONG_HORIZON_DURATION="${PARKSIM_LONG_HORIZON_SECONDS:-900}"
export PARKSIM_BENCH_BACKGROUND_MODES="${PARKSIM_LONG_BACKGROUND_MODES:-human_mixed}"
export PARKSIM_BENCH_TRAFFIC_FLOW_MODE="${PARKSIM_LONG_TRAFFIC_FLOW_MODE:-human_mixed_long_horizon}"
export PARKSIM_BENCH_AGENTS="${PARKSIM_LONG_AGENTS:-rule_based greedy_nearest greedy_shortest_path risk_aware_rule bundle_risk_aware conflict_aware_bundle reservation_bundle rolling_horizon_bundle centralized_min_cost oracle_intent_bundle qwen_vla}"
export PARKSIM_BENCH_SEEDS="${PARKSIM_LONG_SEEDS:-0 1 2 3 4}"
export PARKSIM_BENCH_SPAWN_ENTERING="${PARKSIM_LONG_SPAWN_ENTERING:-90}"
export PARKSIM_BENCH_SPAWN_EXITING="${PARKSIM_LONG_SPAWN_EXITING:-70}"
export PARKSIM_BENCH_RESTORE_OBSTACLES_AS_EXIT_VEHICLES="${PARKSIM_LONG_RESTORE_OBSTACLES_AS_EXIT_VEHICLES:-true}"
export PARKSIM_BENCH_STATIC_OBSTACLE_EXIT_FRACTION="${PARKSIM_LONG_STATIC_OBSTACLE_EXIT_FRACTION:-0.35}"
export PARKSIM_BENCH_STATIC_OBSTACLE_EXIT_MAX="${PARKSIM_LONG_STATIC_OBSTACLE_EXIT_MAX:-40}"
export PARKSIM_BENCH_STATIC_OBSTACLE_EXIT_START_TIME="${PARKSIM_LONG_STATIC_OBSTACLE_EXIT_START_TIME:-5.0}"
export PARKSIM_BENCH_LONG_HORIZON_ENTER_INTERVAL_MEAN="${PARKSIM_LONG_ENTER_INTERVAL_MEAN:-8.0}"
export PARKSIM_BENCH_LONG_HORIZON_EXIT_INTERVAL_MEAN="${PARKSIM_LONG_EXIT_INTERVAL_MEAN:-11.0}"
export PARKSIM_BENCH_HUMAN_INTENT_HIDDEN_FRACTION="${PARKSIM_LONG_HIDDEN_INTENT_FRACTION:-0.75}"
export PARKSIM_BENCH_MAX_CONCURRENT_BACKGROUND_VEHICLES="${PARKSIM_LONG_MAX_CONCURRENT_BACKGROUND_VEHICLES:-120}"
export PARKSIM_BENCH_EXIT_SPOT_REUSE_DELAY="${PARKSIM_LONG_EXIT_SPOT_REUSE_DELAY:-20.0}"
export PARKSIM_BENCH_QWEN_PERIODIC_REPLAN="${PARKSIM_LONG_QWEN_PERIODIC_REPLAN:-true}"
export PARKSIM_BENCH_EARLY_STOP="${PARKSIM_LONG_EARLY_STOP:-0}"
export PARKSIM_BENCH_QWEN_MODE="${PARKSIM_LONG_QWEN_MODE:-real}"
export PARKSIM_BENCH_QWEN_TIMEOUT="${PARKSIM_LONG_QWEN_TIMEOUT:-180.0}"
export PARKSIM_BENCH_REQUIRE_COMPLETE="${PARKSIM_LONG_REQUIRE_COMPLETE:-0}"
export PARKSIM_BENCH_TRAFFIC_COMPLETION_STOP="${PARKSIM_LONG_TRAFFIC_COMPLETION_STOP:-0}"
export PARKSIM_BENCH_TRAFFIC_HORIZON_STOP="${PARKSIM_LONG_TRAFFIC_HORIZON_STOP:-1}"
export PARKSIM_BENCH_TRAFFIC_HORIZON_OVERRUN_SECONDS="${PARKSIM_LONG_TRAFFIC_HORIZON_OVERRUN_SECONDS:-0}"

echo "long_horizon_out_dir=$OUT_DIR"
echo "duration=$PARKSIM_BENCH_DURATION agents=$PARKSIM_BENCH_AGENTS seeds=$PARKSIM_BENCH_SEEDS"
echo "traffic=$PARKSIM_BENCH_TRAFFIC_FLOW_MODE enter=$PARKSIM_BENCH_SPAWN_ENTERING exit=$PARKSIM_BENCH_SPAWN_EXITING hidden=$PARKSIM_BENCH_HUMAN_INTENT_HIDDEN_FRACTION"
echo "stop: early=$PARKSIM_BENCH_EARLY_STOP completion=$PARKSIM_BENCH_TRAFFIC_COMPLETION_STOP horizon=$PARKSIM_BENCH_TRAFFIC_HORIZON_STOP overrun=$PARKSIM_BENCH_TRAFFIC_HORIZON_OVERRUN_SECONDS"
exec "$ROOT/scripts/run_vla_benchmark.sh"
