#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "$ROOT/scripts/training_guard.sh"
parksim_guard_active_training "ParkSim TR-C 3600 s calibration"

OUT_DIR="${PARKSIM_CALIBRATION_OUT_DIR:-$ROOT/experiments/qwen_vla_paper_suite/trc_calibration_$(date +%Y%m%d_%H%M%S)}"
REPORT_NAME="${PARKSIM_CALIBRATION_REPORT_NAME:-calibration_report}"

# One paired, medium-density 3600 s scenario validates the full data path before
# launching the 630-episode journal matrix. It is calibration evidence only.
export PARKSIM_SUITE_OUT_DIR="$OUT_DIR"
export PARKSIM_SUITE_REPORT_NAME="$REPORT_NAME"
export PARKSIM_SUITE_AGENTS="${PARKSIM_CALIBRATION_AGENTS:-rule_based reservation_bundle centralized_min_cost fleet_min_cost mllm_direct mllm_external_feedback}"
export PARKSIM_SUITE_REFERENCE_AGENT="${PARKSIM_CALIBRATION_REFERENCE_AGENT:-mllm_external_feedback}"
export PARKSIM_SUITE_SEEDS="${PARKSIM_CALIBRATION_SEEDS:-0}"
export PARKSIM_SUITE_BACKGROUND_MODES="${PARKSIM_CALIBRATION_BACKGROUND_MODES:-mixed}"
export PARKSIM_SUITE_DENSITY_CONFIGS="${PARKSIM_CALIBRATION_DENSITY_CONFIGS:-medium:450:338:11.4286:15.7143:26.6667:36.6667}"
export PARKSIM_SUITE_DURATION="${PARKSIM_CALIBRATION_DURATION:-3600s}"
export PARKSIM_SUITE_QWEN_MODE="${PARKSIM_CALIBRATION_QWEN_MODE:-real}"
export PARKSIM_SUITE_QWEN_TIMEOUT="${PARKSIM_CALIBRATION_QWEN_TIMEOUT:-180.0}"
export PARKSIM_SUITE_FLEET_DECISION_PERIOD="${PARKSIM_CALIBRATION_FLEET_DECISION_PERIOD:-30.0}"
export PARKSIM_SUITE_FLEET_DECISION_ACK_TIMEOUT="${PARKSIM_CALIBRATION_FLEET_DECISION_ACK_TIMEOUT:-10.0}"
export PARKSIM_SUITE_TRAFFIC_FLOW_MODE=human_mixed_long_horizon
export PARKSIM_SUITE_FLEET_CONTROL_MODE=cloud_av
export PARKSIM_SUITE_ENTRY_VEHICLE_AGENT_TYPE=__agent__
export PARKSIM_SUITE_EXIT_VEHICLE_AGENT_TYPE=__agent__
export PARKSIM_SUITE_AV_SPAWN_ENTERING="${PARKSIM_CALIBRATION_AV_SPAWN_ENTERING:-280}"
export PARKSIM_SUITE_AV_SPAWN_EXITING="${PARKSIM_CALIBRATION_AV_SPAWN_EXITING:-200}"
export PARKSIM_SUITE_RESTORE_OBSTACLES_AS_EXIT_VEHICLES=true
export PARKSIM_SUITE_HUMAN_INTENT_HIDDEN_FRACTION=0.75
export PARKSIM_SUITE_MAX_CONCURRENT_BACKGROUND_VEHICLES=120
export PARKSIM_SUITE_REQUIRE_COMPLETE=0
export PARKSIM_SUITE_EARLY_STOP=0
export PARKSIM_SUITE_TRAFFIC_COMPLETION_STOP=0
export PARKSIM_SUITE_TRAFFIC_HORIZON_STOP=1
export PARKSIM_SUITE_TRAFFIC_HORIZON_OVERRUN_SECONDS=0
export PARKSIM_SUITE_GATE_PROFILE=pilot
export PARKSIM_SUITE_GATE_STRICT=0
export PARKSIM_SUITE_GATE_REQUIRE_VIDEO=0
export PARKSIM_SUITE_GATE_SKIP_VIDEO=1
export PARKSIM_SUITE_GATE_SKIP_MANUSCRIPT=1
export PARKSIM_SUITE_TRC_ANALYSIS=1
export PARKSIM_SUITE_CRITICAL_STATE_ANALYSIS=1
export PARKSIM_SUITE_WINDOW_METRICS=1
export PARKSIM_SUITE_WINDOW_SECONDS=300.0
export PARKSIM_SUITE_RESUME=1
export PARKSIM_SUITE_CONTINUE_ON_FAIL=0
export PARKSIM_SUITE_PROTECT_ACTIVE_TRAINING=1
export PARKSIM_SUITE_ALLOW_DURING_TRAINING=0

"$ROOT/scripts/run_vla_paper_suite.sh"
