#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Journal-scale defaults are intentionally expensive. Use PARKSIM_SUITE_DRY_RUN=1
# to inspect the matrix before launching the full experiment.
export PARKSIM_SUITE_GATE_PROFILE="${PARKSIM_SUITE_GATE_PROFILE:-trc}"
export PARKSIM_SUITE_GATE_STRICT="${PARKSIM_SUITE_GATE_STRICT:-1}"
export PARKSIM_SUITE_QWEN_MODE="${PARKSIM_SUITE_QWEN_MODE:-real}"
export PARKSIM_SUITE_REQUIRE_COMPLETE="${PARKSIM_SUITE_REQUIRE_COMPLETE:-0}"
export PARKSIM_SUITE_EARLY_STOP="${PARKSIM_SUITE_EARLY_STOP:-0}"
export PARKSIM_SUITE_SEEDS="${PARKSIM_SUITE_SEEDS:-0 1 2 3 4}"
export PARKSIM_SUITE_BACKGROUND_MODES="${PARKSIM_SUITE_BACKGROUND_MODES:-rule_random mixed replay}"
export PARKSIM_SUITE_DENSITY_CONFIGS="${PARKSIM_SUITE_DENSITY_CONFIGS:-empty:0:0 light:2:1 balanced:4:4 dense:8:8 saturated:12:12}"
export PARKSIM_SUITE_DURATION="${PARKSIM_SUITE_DURATION:-900s}"
export PARKSIM_SUITE_TRAFFIC_FLOW_MODE="${PARKSIM_SUITE_TRAFFIC_FLOW_MODE:-human_mixed_long_horizon}"
export PARKSIM_SUITE_FLEET_CONTROL_MODE="${PARKSIM_SUITE_FLEET_CONTROL_MODE:-cloud_av}"
export PARKSIM_SUITE_ENTRY_VEHICLE_AGENT_TYPE="${PARKSIM_SUITE_ENTRY_VEHICLE_AGENT_TYPE:-__agent__}"
export PARKSIM_SUITE_EXIT_VEHICLE_AGENT_TYPE="${PARKSIM_SUITE_EXIT_VEHICLE_AGENT_TYPE:-__agent__}"
export PARKSIM_SUITE_AV_SPAWN_ENTERING="${PARKSIM_SUITE_AV_SPAWN_ENTERING:-30}"
export PARKSIM_SUITE_AV_SPAWN_EXITING="${PARKSIM_SUITE_AV_SPAWN_EXITING:-20}"
export PARKSIM_SUITE_RESTORE_OBSTACLES_AS_EXIT_VEHICLES="${PARKSIM_SUITE_RESTORE_OBSTACLES_AS_EXIT_VEHICLES:-true}"
export PARKSIM_SUITE_HUMAN_INTENT_HIDDEN_FRACTION="${PARKSIM_SUITE_HUMAN_INTENT_HIDDEN_FRACTION:-0.75}"
export PARKSIM_SUITE_MAX_CONCURRENT_BACKGROUND_VEHICLES="${PARKSIM_SUITE_MAX_CONCURRENT_BACKGROUND_VEHICLES:-120}"
export PARKSIM_SUITE_LONG_HORIZON_ENTER_INTERVAL_MEAN="${PARKSIM_SUITE_LONG_HORIZON_ENTER_INTERVAL_MEAN:-8.0}"
export PARKSIM_SUITE_LONG_HORIZON_EXIT_INTERVAL_MEAN="${PARKSIM_SUITE_LONG_HORIZON_EXIT_INTERVAL_MEAN:-11.0}"
export PARKSIM_SUITE_REPLAY_ALL_DENSITIES="${PARKSIM_SUITE_REPLAY_ALL_DENSITIES:-0}"
export PARKSIM_SUITE_GATE_REQUIRE_VIDEO="${PARKSIM_SUITE_GATE_REQUIRE_VIDEO:-1}"
export PARKSIM_SUITE_TRAFFIC_COMPLETION_STOP="${PARKSIM_SUITE_TRAFFIC_COMPLETION_STOP:-0}"
export PARKSIM_SUITE_TRAFFIC_HORIZON_STOP="${PARKSIM_SUITE_TRAFFIC_HORIZON_STOP:-1}"
export PARKSIM_SUITE_TRAFFIC_HORIZON_OVERRUN_SECONDS="${PARKSIM_SUITE_TRAFFIC_HORIZON_OVERRUN_SECONDS:-0}"

exec "$ROOT/scripts/run_vla_paper_suite.sh"
